services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runtelegrambot
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: unless-stopped
